# Base da imagem
FROM ubuntu:latest

# Atualiza o sistema e instala o iptables
RUN apt-get update && \
    apt-get install -y iptables iproute2 iputils-ping isc-dhcp-server && \
    apt-get clean

# Habilita o roteamento de pacotes (IP Forwarding)
RUN sysctl -w net.ipv4.ip_forward=1

# Copia o script de configuração do firewall para o container
# COPY iptables-rules.sh /usr/local/bin/iptables-rules.sh

# Garante permissão de execução para o script
# RUN chmod +x /usr/local/bin/iptables-rules.sh
COPY dhcpd.conf /etc/dhcp/dhcpd.conf

COPY isc-dhcp-server /etc/default/isc-dhcp-server

# Executa o script e mantém o container ativo
# CMD /bin/bash -c "/usr/local/bin/iptables-rules.sh && tail -f /dev/null"
CMD ["sh", "-c", "rm -f /var/run/dhcpd.pid && service isc-dhcp-server start && tail -f /dev/null"]
