version: '3.8'

services:
  # Sub-rede A
  web_a:
    image: ubuntu
    container_name: web_a
    networks:
      subnet_a:
    command: dhclient

  dns_a:
    image: ubuntu
    container_name: dns_a
    networks:
      subnet_a:
    command: tail -f /dev/null

  host_a1:
    image: ubuntu
    container_name: host_a1
    networks:
      subnet_a:
    command: dhclient

  host_a2:
    image: ubuntu
    container_name: host_a2
    networks:
      subnet_a:
    command: dhclient

  # Sub-rede B
  web_b:
    image: ubuntu
    container_name: web_b
    networks:
      subnet_b:
    command: dhclient

  dns_b:
    image: ubuntu
    container_name: dns_b
    networks:
      subnet_b:
    command: tail -f /dev/null

  host_b1:
    image: ubuntu
    container_name: host_b1
    networks:
      subnet_b:
    command: dhclient

  host_b2:
    image: ubuntu
    container_name: host_b2
    networks:
      subnet_b:
    command: dhclient

  # Firewall/Router + DHCP
  firewall:
    image: ubuntu
    container_name: firewall
    networks:
      subnet_a:
        ipv4_address: 10.0.0.254
      subnet_b:
        ipv4_address: 20.0.0.254
    cap_add:
      - NET_ADMIN
    volumes:
      - ./dhcpd.conf:/etc/dhcp/dhcpd.conf
    command: bash -c "apt-get update && apt-get install -y isc-dhcp-server && service isc-dhcp-server start && tail -f /dev/null"

networks:
  subnet_a:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.254
  subnet_b:
    driver: bridge
    ipam:
      config:
        - subnet: 20.0.0.0/24
          gateway: 20.0.0.254
