version: '3.8'

services:
  # Sub-rede A
  web_a:
    build:
      context: ./subrede_a/web_a
    container_name: web_a
    hostname: web_a  
    networks:
      subnet_a:
    privileged: true  

  dns_a:
    build:
      context: ./subrede_a/dns_a
    container_name: dns_a
    hostname: dns_a  
    networks:
      subnet_a:
    privileged: true  

  host_a1:
    build:
      context: ./subrede_a/host1
    container_name: host_a1
    hostname: host_a1  
    networks:
      subnet_a:
    cap_add:
      - NET_ADMIN  
    privileged: true  

  host_a2:
    build:
      context: ./subrede_a/host2
    container_name: host_a2
    hostname: host_a2  
    networks:
      subnet_a:
    privileged: true  

  # Sub-rede B
  web_b:
    build:
      context: ./subrede_b/web_b
    container_name: web_b
    hostname: web_b  
    networks:
      subnet_b:
    privileged: true  

  dns_b:
    build:
      context: ./subrede_b/dns_b
    container_name: dns_b
    hostname: dns_b  
    networks:
      subnet_b:
    privileged: true  

  host_b1:
    build:
      context: ./subrede_b/host1
    container_name: host_b1
    hostname: host_b1  
    networks:
      subnet_b:
    cap_add:
      - NET_ADMIN 
    privileged: true  

  host_b2:
    build:
      context: ./subrede_b/host2
    container_name: host_b2
    hostname: host_b2  
    networks:
      subnet_b:
    privileged: true  

  firewall:
    build: ./firewall  
    container_name: firewall
    hostname: firewall  
    networks:
      subnet_a:
      subnet_b:
    cap_add:
      - NET_ADMIN
    volumes:
      - ./firewall/dhcpd.conf:/etc/dhcp/dhcpd.conf  
    privileged: true  

# Sub-Redes
networks:
  subnet_a:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24

  subnet_b:
    driver: bridge
    ipam:
      config:
        - subnet: 20.0.0.0/24