FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y curl iputils-ping net-tools iproute2 vim isc-dhcp-client && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


CMD ["sh", "-c", "sleep infinity"]