FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y bind9 bind9utils bind9-doc dnsutils vim isc-dhcp-client && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY ./named.conf.local /etc/bind/named.conf.local
COPY ./db.empresa-b.com /etc/bind/db.empresa-b.com


CMD ["named", "-g"]