FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y apache2 iproute2 vim isc-dhcp-client net-tools && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY index.html /var/www/html/index.html

CMD ["apache2ctl", "-D", "FOREGROUND"]